#ifndef TCPSTATUSCODE_H
#define TCPSTATUSCODE_H

enum class TcpStatusCode
{
    SUCCESS = 200,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    INTERNAL_ERROR = 500,
    SERVICE_UNAVAILABLE = 503,
    TIMEOUT = 408,
    RETRY_LATER = 429
};

#endif // TCPSTATUSCODE_H
