#ifndef TCPSTATUSCODE_H
#define TCPSTATUSCODE_H

enum class TcpStatusCode
{
    UNKNOWN = 000,
    SUCCESS = 200,
    FORBIDDEN = 403,
    TIMEOUT = 408,
    SOCKET_ERROR_CODE = 100,
    CONNECTION_ERROR = 101,
    SEND_ERROR = 102,
    RECEIVE_ERROR = 103,
    INVALID_IP_ERROR = 104
};

#endif // TCPSTATUSCODE_H
